### ISSUE TITLE
Execute option in interactive does not work

### ISSUE THREAD

**Issue by PennyQ** [maxwelltsai/SiMon#27]
@maxwelltsai  Error as below:
> Please choose an action to continue: x
Traceback (most recent call last):
  File "simon.py", line 425, in <module>
    s.interactive_mode()
  File "simon.py", line 394, in interactive_mode
    self.task_handler(choice)
  File "simon.py", line 258, in task_handler
    self.sim_inst_dict[sid].sim_shell_exec()
TypeError: sim_shell_exec() takes exactly 2 arguments (1 given)

**Comment by maxwelltsai** [comment]
Fixed in #32
