### ISSUE TITLE
python deemon.py stop causes error

### ISSUE THREAD

**Issue by PennyQ** [maxwelltsai/SiMon#28]
@maxwelltsai Error as below:
> ➜  SiMon git:(add_test_script) ✗ python simon.py stop
Traceback (most recent call last):
  File "simon.py", line 419, in <module>
    s.daemon_mode()
  File "simon.py", line 408, in daemon_mode
    daemon_runner.do_action()  # fixed time period of calling run()
  File "/Users/penny/anaconda/lib/python2.7/site-packages/daemon/runner.py", line 267, in do_action
    func(self)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/daemon/runner.py", line 217, in _stop
    raise error
daemon.runner.DaemonRunnerStopFailureError: PID file '/Users/penny/Works/simon_project/nbody6/Ncode/run/run_mgr_daemon.pid' not locked

**Comment by maxwelltsai** [comment]
@PennyQ This means that the daemon is not yet started. If you run ``python simon.py start'' and then run ``python simon.py stop'', I believe that there will be no more error. This error occurs only if you run ``python simon.py stop'' BEFORE running ``python simon.py start''. Nevertheless, it is a good idea to catch the exception and tell the users to start the daemon first.

**Comment by PennyQ** [comment]
@maxwelltsai the error is still the same after I ran `python simon.py start` as below:
> ➜  SiMon git:(add_test_script) ✗ python simon.py start
➜  SiMon git:(add_test_script) ✗ python simon.py stop
Traceback (most recent call last):
  File "simon.py", line 419, in <module>
    s.daemon_mode()
  File "simon.py", line 408, in daemon_mode
    daemon_runner.do_action()  # fixed time period of calling run()
  File "/Users/penny/anaconda/lib/python2.7/site-packages/daemon/runner.py", line 267, in do_action
    func(self)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/daemon/runner.py", line 217, in _stop
    raise error
daemon.runner.DaemonRunnerStopFailureError: PID file '/Users/penny/Works/simon_project/nbody6/Ncode/run/run_mgr_daemon.pid' not locked

**Comment by maxwelltsai** [comment]
Fixed in #32
